services:
  # Backend service for development
  backend-dev:
    build:
      context: ./be
      dockerfile: Dockerfile
      target: builder  # Use the builder stage for development
    container_name: bumasys-backend-dev
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET:-dev-jwt-secret-key}
      - DB_FILE=/app/data/database.json
      - BETTER_STACK_ENABLED=false
    volumes:
      # Mount source code for development
      - ./be/src:/app/src:ro
      - ./be/config:/app/config:ro
      # Persist database
      - backend_dev_data:/app/data
    networks:
      - bumasys-dev-network
    command: ["pnpm", "dev"]
    restart: unless-stopped

  # Frontend service for development
  frontend-dev:
    build:
      context: ./fe
      dockerfile: Dockerfile
      target: builder  # Use the builder stage for development
    container_name: bumasys-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4000
    volumes:
      # Mount source code for development
      - ./fe/src:/app/src:ro
      - ./fe/public:/app/public:ro
    depends_on:
      - backend-dev
    networks:
      - bumasys-dev-network
    command: ["pnpm", "dev", "--host", "0.0.0.0"]
    restart: unless-stopped

volumes:
  # Persistent volume for backend database in development
  backend_dev_data:
    driver: local

networks:
  # Internal network for development services communication
  bumasys-dev-network:
    driver: bridge