services:
  # Backend service
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: bumasys-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      - DB_FILE=/app/data/database.json
      - BETTER_STACK_ENABLED=${BETTER_STACK_ENABLED:-false}
      - BETTER_STACK_SOURCE_TOKEN=${BETTER_STACK_SOURCE_TOKEN:-}
    volumes:
      # Persist database
      - backend_data:/app/data
    networks:
      - bumasys-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/graphql?query={__typename}', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: bumasys-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - bumasys-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

volumes:
  # Persistent volume for backend database
  backend_data:
    driver: local

networks:
  # Internal network for services communication
  bumasys-network:
    driver: bridge