services:
  # Backend service
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: bumasys-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - FCRM_PORT=4000
      - FCRM_JWT_SECRET=${FCRM_JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      - FCRM_DB_FILE=/data/db.json
      - FCRM_BETTER_STACK_ENABLED=${FCRM_BETTER_STACK_ENABLED:-false}
      - FCRM_BETTER_STACK_SOURCE_TOKEN=${FCRM_BETTER_STACK_SOURCE_TOKEN:-}
    volumes:
      # Persist database
      - backend_data:/data
    networks:
      - bumasys-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: bumasys-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - bumasys-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

volumes:
  # Persistent volume for backend database
  backend_data:
    driver: local

networks:
  # Internal network for services communication
  bumasys-network:
    driver: bridge