/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ChangePasswordCard: typeof import('./components/ChangePasswordCard.vue')['default']
    ComplexityCreateDialog: typeof import('./components/ComplexityCreateDialog.vue')['default']
    ComplexityDeleteDialog: typeof import('./components/ComplexityDeleteDialog.vue')['default']
    ComplexityEditDialog: typeof import('./components/ComplexityEditDialog.vue')['default']
    ConfigDisplayCard: typeof import('./components/ConfigDisplayCard.vue')['default']
    DebugInfoCard: typeof import('./components/DebugInfoCard.vue')['default']
    DepartmentCreateDialog: typeof import('./components/DepartmentCreateDialog.vue')['default']
    DepartmentDeleteDialog: typeof import('./components/DepartmentDeleteDialog.vue')['default']
    DepartmentEditDialog: typeof import('./components/DepartmentEditDialog.vue')['default']
    LoginCard: typeof import('./components/LoginCard.vue')['default']
    LogoutCard: typeof import('./components/LogoutCard.vue')['default']
    OrganizationCreateDialog: typeof import('./components/OrganizationCreateDialog.vue')['default']
    OrganizationDeleteDialog: typeof import('./components/OrganizationDeleteDialog.vue')['default']
    OrganizationEditDialog: typeof import('./components/OrganizationEditDialog.vue')['default']
    OrganizationViewDialog: typeof import('./components/OrganizationViewDialog.vue')['default']
    PasswordResetCard: typeof import('./components/PasswordResetCard.vue')['default']
    PriorityCreateDialog: typeof import('./components/PriorityCreateDialog.vue')['default']
    PriorityDeleteDialog: typeof import('./components/PriorityDeleteDialog.vue')['default']
    PriorityEditDialog: typeof import('./components/PriorityEditDialog.vue')['default']
    ProfileCard: typeof import('./components/ProfileCard.vue')['default']
    RegisterCard: typeof import('./components/RegisterCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StaffCreateDialog: typeof import('./components/StaffCreateDialog.vue')['default']
    StaffDeleteDialog: typeof import('./components/StaffDeleteDialog.vue')['default']
    StaffEditDialog: typeof import('./components/StaffEditDialog.vue')['default']
    StatusCreateDialog: typeof import('./components/StatusCreateDialog.vue')['default']
    StatusDeleteDialog: typeof import('./components/StatusDeleteDialog.vue')['default']
    StatusEditDialog: typeof import('./components/StatusEditDialog.vue')['default']
    UserCreateDialog: typeof import('./components/UserCreateDialog.vue')['default']
    UserDeleteDialog: typeof import('./components/UserDeleteDialog.vue')['default']
    UserEditDialog: typeof import('./components/UserEditDialog.vue')['default']
    UserViewDialog: typeof import('./components/UserViewDialog.vue')['default']
  }
}
