/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ChangePasswordCard: typeof import('./components/ChangePasswordCard.vue')['default']
    copy: typeof import('./components/HomeCard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeCard: typeof import('./components/HomeCard.vue')['default']
    LoginCard: typeof import('./components/LoginCard.vue')['default']
    LogoutCard: typeof import('./components/LogoutCard.vue')['default']
    PasswordResetCard: typeof import('./components/PasswordResetCard.vue')['default']
    ProfileCard: typeof import('./components/ProfileCard.vue')['default']
    RegisterCard: typeof import('./components/RegisterCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserCreateDialog: typeof import('./components/UserCreateDialog.vue')['default']
    UserDeleteDialog: typeof import('./components/UserDeleteDialog.vue')['default']
    UserEditDialog: typeof import('./components/UserEditDialog.vue')['default']
    UserViewDialog: typeof import('./components/UserViewDialog.vue')['default']
  }
}
