/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/budget': RouteRecordInfo<'/budget', '/budget', Record<never, never>, Record<never, never>>,
    '/people': RouteRecordInfo<'/people', '/people', Record<never, never>, Record<never, never>>,
    '/references': RouteRecordInfo<'/references', '/references', Record<never, never>, Record<never, never>>,
    '/task-management/[id]': RouteRecordInfo<'/task-management/[id]', '/task-management/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/tasks': RouteRecordInfo<'/tasks', '/tasks', Record<never, never>, Record<never, never>>,
    '/teams': RouteRecordInfo<'/teams', '/teams', Record<never, never>, Record<never, never>>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>>,
  }
}
